//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>

extern volatile int mS_counter;
extern volatile int LED_OUTPUT;

SI_SBIT(LED_D22_D23, SFR_P0, 0);
SI_SBIT(LED_D9, SFR_P0, 1);
SI_SBIT(LED_D10, SFR_P0, 2);
SI_SBIT(LED_D18_D19_D20_D21, SFR_P0, 3);
SI_SBIT(LED_D8, SFR_P0, 4);
SI_SBIT(LED_D7, SFR_P0, 5);
SI_SBIT(LED_D11_D12_D17, SFR_P0, 6);
SI_SBIT(LED_D13, SFR_P0, 7);

SI_SBIT(LED_D14_D15_D16, SFR_P1, 0);
SI_SBIT(LED_D4, SFR_P1, 1);
SI_SBIT(LED_D3, SFR_P1, 2);
SI_SBIT(LED_D2, SFR_P1, 3);
SI_SBIT(LED_D5, SFR_P1, 5);
SI_SBIT(LED_D6, SFR_P1, 6);
SI_SBIT(LED_D1, SFR_P1, 7);

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
	mS_counter++;

	LED_D1 = LED_OUTPUT & 0x0001;
	LED_D2 = LED_OUTPUT & 0x0002;
	LED_D3 = LED_OUTPUT & 0x0004;
	LED_D4 = LED_OUTPUT & 0x0008;
	LED_D5 = LED_OUTPUT & 0x0010;
	LED_D6 = LED_OUTPUT & 0x0020;
	LED_D7 = LED_OUTPUT & 0x0040;
	LED_D8 = LED_OUTPUT & 0x0080;
	LED_D9 = LED_OUTPUT & 0x0100;
	LED_D10 = LED_OUTPUT & 0x0200;
	LED_D13 = LED_OUTPUT & 0x0400;
	LED_D11_D12_D17 = LED_OUTPUT & 0x0800;
	LED_D14_D15_D16 = LED_OUTPUT & 0x1000;
	LED_D18_D19_D20_D21 = LED_OUTPUT & 0x2000;
	LED_D22_D23 = LED_OUTPUT & 0x4000;

	TCON_TF0 = 0;
}

